API/urls.py
from django.urls import path

from . import views
#API
app_name = 'API'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('weather/', views.weather, name= 'weather')
]

polls_site/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main_page.urls')),

    #path('register/', include('users.urls')),
    path('user/', include('users.urls', namespace='user')),

    path('API/', include('API.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),
]

API/models.py
from django.db import models

# Create your models here.

API/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .weather_get import get_temperature, api_key, evaluation
# Create your views here.

@login_required
def index(request):
    return render(request, 'API/index.html')

@login_required
def weather(request):
    if request.method == 'GET':
        city_name = request.GET.get('site', 'Kiev')
    else:
        city_name = 'Kiev'

    try:
        temperature, data_json = get_temperature(city_name=city_name, api_key=api_key)
        eval = evaluation(data_json)
    except Exception as e:
        temperature = 'Write the correct name of the city'
        data_json = "Write the correct name of the city"
        eval = 'Unknown'


    context = {
        'temperature': temperature,
        'data_text': data_json,
        'evaluation': eval
    }
    return render(request, 'API/weather.html', context)

API/templates/API/index.html
{% extends 'API/index_templ.html' %}

{% load static %}

{% block index %}
<button class="custom-btn-acpt-cncl btn-acpt-cncl" onclick="window.location.href='{% url 'API:weather' %}'"> Chek weather in any city </button>
{% endblock %}

API/templates/API/index_templ.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Polls</title>
    <link rel="stylesheet" href="{% static 'API/style_ind.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'API/img/favicon.ico' %}">
</head>
<body>
    <div class="mainComponent">

        <div class="head">
            <header>
                <h1><a href="/">Home</a></h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="/about_us">About us</a></p>
                        <p><a href="/polls">Polls</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
            </header>
        </div>
        {% block index %}{% endblock %}
        {% block weatherAPI %}{% endblock %}
    </div>
</body>
</html>

API/templates/API/weather.html
{% extends 'API/index_templ.html' %}

{% block weatherAPI %}
    {% load static %}
        <script src="{% static 'API/copy.js' %}"></script>
        <link rel="stylesheet" href="{% static 'API/style_ind.css'%}">

    <form id="search-field" action="{% url 'API:weather' %}">
      <input type="checkbox" id="show-search-field" />
      <label for="show-search-field"><span>Kiev</span></label>
      <span>
        <input type="text" id="site" name="site" placeholder="Write city name" />
        <button type="submit" form="search-field" title="Submit">&nbsp;</button>
      </span>
    </form>

    <div class="temperature">
        <p>{{ temperature }}</p>
        {% if evaluation == 'Hot'%}
            <img src="{% static 'API/img/hot.png' %}">
        {% elif evaluation == 'Normal' %}
            <img src="{% static 'API/img/normal.png' %}">
        {% elif evaluation == 'Unknown' %}
            <img src="{% static 'API/img/error.png' %}">
        {% else %}
            <img src="{% static 'API/img/cold.png' %}">
        {% endif %}
    </div>
    <div id = "div1"class="code-box">
      <h2>Info taken from openweathermap.org</h2>
      <pre><code id="shit" class="code-block">the data is: {{data_text}}</code></pre>
          <button onclick="CopyToClipboard(document.getElementById('shit'))" class="copy-btn">Copy</button>
    </div>
{% endblock %}