API/urls.py
from django.urls import path

from . import views
#API
app_name = 'API'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('weather/', views.weather, name= 'weather')
]

main_page/urls.py
from django.urls import path

from . import views

app_name = 'main_page'
urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name= 'about_us')
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name= 'detail'),
    path('<int:question_id>/results', views.results, name= 'results'),
    path('<int:question_id>/remove_vote/', views.remove_vote, name='remove_vote'),
    path('<int:question_id>/vote', views.vote, name= 'vote'),
]

polls_site/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main_page.urls')),

    #path('register/', include('users.urls')),
    path('user/', include('users.urls', namespace='user')),

    path('API/', include('API.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
#updated
from users.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days= 1)
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

#updated
class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} voted on {self.question.question_text} for {self.choice.choice_text}'

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import Question, Choice, Vote
from .utils import has_voted

# Create your views here.

@login_required
def index(request):
    order_by = request.GET.get('order_by', '-pub_date')
    latest_question_list = Question.objects.order_by(order_by)[:]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)
@login_required
def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    conext = {
        'question': question
    }
    return render(request, 'polls/detail.html', conext)

@login_required
def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    context = {
        'question' : question,
    }
    return render(request, 'polls/results.html', context)


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
        'error_messege': 'You didnt select a choice.'
    }

    # If user doesnt vote in poll
    if Vote.objects.filter(user=request.user, question=question).exists():
        return render(request, 'polls/alrd_voted.html', {'question': question})

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', context)
    else:
        selected_choice.votes += 1
        selected_choice.save()

        # Создаем запись о голосовании в таблице Vote
        vote = Vote(user=request.user, question=question, choice=selected_choice)
        vote.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@login_required
def remove_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    # Find the vote made by the user for the current question
    try:
        vote = Vote.objects.get(user=request.user, question=question)
    except Vote.DoesNotExist:
        return HttpResponse('You have not voted in this poll.')

    # Remove the vote and update the choice count
    choice = vote.choice
    choice.votes -= 1
    choice.save()
    vote.delete()

    return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))

polls/templates/polls/alrd_voted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
    {% load static%}
    <link rel="stylesheet" href="{% static 'polls/style_ind.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'polls/img/favicon.ico' %}">
</head>
<body>
     <div class="head">
            <header>
                <h1>Polls</h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="/about_us">About us</a></p>
                        <p><a href="/">Home</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
            </header>
        </div>
     <div class="votes">
        <h>You have already voted for this poll.</h>
     </div>
     <div class="mainComponent">
         <form method="POST" action="{% url 'polls:remove_vote' question.id %}">
            {% csrf_token %}
            <button class="custom-btn-acpt-cncl btn-acpt-cncl" type="submit"> Remove Vote </button>
        </form>
        <button class="custom-btn-acpt-cncl btn-acpt-cncl" onclick="window.location.href='{% url 'polls:index'%}'"> Back to polls </button>
     </div>
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
    {% load static%}
    <link rel="stylesheet" href="{% static 'polls/style_detail.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'polls/img/favicon.ico' %}">
</head>
<body>
<div class="mainComponent">


     <div class="head">
            <header>
                <h1>Polls</h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="{% url 'main_page:about_us' %}">About us</a></p>
                        <p><a href="/">Home</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
            </header>
        </div>


    <form action="{% url 'polls:vote' question.id%}" method="post">
        {% csrf_token %}
        <div class="wrapper">
        <a href="{% url 'polls:index' %}" class="custom-btn-acpt-cncl btn-acpt-cncl">Back to Polls</a>


        <legend>{{ question.question_text }}</legend>

        <div class="date">
            <p>{{ question.pub_date}}</p>
        </div>
        <div class="poll">
            <fieldset>
                {% if error_messege %}
                    <p><strong> {{ error_maessage }} </strong></p>
                {% endif%}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
                    <label for="choice{{forloop.counter}}" > {{ choice.choice_text }} </label><br>
                {% endfor %}
            </fieldset>
        </div>
            <input class="custom-btn-acpt-cncl btn-acpt-cncl" type="submit" value="Vote">
        </div>

    </form>
</div>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
    {% load static%}
    <script src="{% static 'polls/sort.js' %}"></script>
    <link rel="stylesheet" href="{% static 'polls/style_ind.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'polls/img/favicon.ico' %}">
</head>
<body>
     <div class="head">
            <header>
                <h1>Polls</h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="/about_us">About us</a></p>
                        <p><a href="/">Home</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
            </header>
        </div>

       <div class="container" onclick="toggleSortButton(this)">
          <div class="bar1"></div>
          <div class="bar2"></div>
          <div class="bar3"></div>
       </div>

    {% if latest_question_list %}
            {% for question in latest_question_list %}
                <div class="poll-question">
                    <p>{{question.question_text}}</p>
                    <div class="pol-choice">
                        {% for choice in question.choice_set.all %}
                            <li><label for="choice{{forloop.counter}}" >{{ choice.choice_text }} </label></li>
                        {% endfor %}
                    </div>
                    <div class="to-full-poll">
                        <button class="custom-btn-acpt-cncl btn-acpt-cncl" onclick="window.location.href='{% url 'polls:detail' question.id%}'"> See full poll </button>
                    </div>
                    <div class="date">
                        <p>{{ question.pub_date}}</p>
                    </div>
                </div>
            {% endfor %}
    {% else %}
        <p>No polls for now</p>
    {% endif %}

    </div>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
    {% load static%}
    <link rel="stylesheet" href="{% static 'polls/style_results.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'polls/img/favicon.ico' %}">

</head>
<body>

        <div class="head">
            <header>
                <h1><a href="/">Home</a></h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="/about_us">About us</a></p>
                        <p><a href="/polls">Polls</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
            </header>
        </div>
        <div class = "votes_res">
          <ul>
            <h1>{{ question.question_text }}</h1>
            {% for choice in question.choice_set.all %}
              <p>For {{choice.choice_text}} - {{ choice.votes }} vote{{choice.votes| pluralize }}</p>
            {% endfor %}
          </ul>
{#            <a href="{% url 'polls:index' %}"><button class="custom-btn-acpt-cncl btn-acpt-cncl"> Vote again? </button></a>#}
            <button class="custom-btn-acpt-cncl btn-acpt-cncl" onclick="window.location.href='{% url 'polls:index'%}'"> Back to polls </button>

        </div>

</body>
</html>