API/urls.py
from django.urls import path

from . import views
#API
app_name = 'API'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('weather/', views.weather, name= 'weather')
]

main_page/urls.py
from django.urls import path

from . import views

app_name = 'main_page'
urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name= 'about_us')
]

polls_site/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main_page.urls')),

    #path('register/', include('users.urls')),
    path('user/', include('users.urls', namespace='user')),

    path('API/', include('API.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),
]

users/urls.py
# from django.urls import path, include
# from .views import UserLoginView, SignupView, UserLogoutView
#
# from . import views
#
# app_name = 'users'
#
# urlpatterns = [
#     path('',views.index, name= 'index'),
#     path('account/', views.account, name= 'account'),
#     path(r'login/', UserLoginView.as_view(), name= 'login'),
#     path(r'logout/', UserLogoutView.as_view(), name= 'logout'),
#     #path(r'singup/', SignupView.as_view(), name= 'singup'),
#     path(r'signup/', SignupView.as_view(), name= 'signup'),
#     path('google-auth/', include('social_django.urls', namespace='social')),
# ]


from django.urls import path, include
from .views import UserLoginView, SignupView, UserLogoutView

from . import views

app_name = 'users'

urlpatterns = [
    path('',views.index, name= 'index'),
    path('account/', views.account, name= 'account'),
    path(r'login/', UserLoginView.as_view(), name= 'login'),
    path(r'logout/', UserLogoutView.as_view(), name= 'logout'),
    path(r'singup/', SignupView.as_view(), name= 'singup'),
    #path('google-auth/', include('social_django.urls', namespace='social')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.shortcuts import render

from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request, 'main_page/index.html')

def about_us(request):
    return  render(request, 'main_page/about_us.html')

main_page/templates/main_page/about_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About us</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main_page/style_about.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'main_page/img/favicon.ico' %}">
</head>
<body>
    <div class="mainComponent">
        <div class="head">
            <header>
                <h1>About us</h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="/">Home</a></p>
                        <p><a href="/polls">Polls</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
            </header>
        </div>

        <div class="about_us_intro">
          <p>
            Welcome to our website! We are a team of passionate individuals who believe in the power of technology to make people's lives better. Our goal is to create innovative solutions that address real-world problems and improve the quality of life for everyone. Whether you are a business owner, a student, or a busy parent, we have something for you.
          </p>
        </div>
        <div class="about_us_goal">
          <p>
            Our team consists of experts in various fields, including software development, design, marketing, and project management. We work closely with our clients to understand their unique needs and develop customized solutions that exceed their expectations. With years of experience and a commitment to excellence, we have helped numerous businesses and individuals achieve their goals.
          </p>
        </div>
        <div class="about_us_impact">
          <p>
            At our core, we are driven by a desire to make a positive impact on the world. We believe that technology can be a force for good, and we strive to use our skills and knowledge to create meaningful change. We are constantly learning and growing, and we are dedicated to staying at the forefront of our industry. Thank you for considering us for your next project - we look forward to working with you!
              Also, our project is an open source project. You can find source code <a href="https://github.com/werent4/Polls_web_site" class="git">here</a> or read <a href="https://github.com/werent4/Polls_web_site/blob/main/documentation/general_documentation.pdf" class="git">documentation</a>
          </p>
        </div>

    </div>
</body>
</html>

main_page/templates/main_page/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Polls</title>
    <link rel="stylesheet" href="{% static 'main_page/style_ind.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'main_page/img/favicon.ico' %}">
    <script src="{% static 'main_page/check.js'%}"></script>
</head>
<body>
    <div class="mainComponent">

        <div class="head">
            <header>
                <h1>Home</h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="/about_us">About us</a></p>
                        <p><a href="/polls">Polls</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
{#                   <div class="container" onclick="toggleSortButton(this)">#}
{#                      <div class="bar1"></div>#}
{#                      <div class="bar2"></div>#}
{#                      <div class="bar3"></div>#}
{#                   </div>#}
                    {% if request.user.is_authenticated %}
                        <div class="register">
                            <p>Welcome <a href="{% url 'users:account' %}">{{ user.username }}</a></p>
                            <a href="{% url 'users:logout' %}"><button class="custom-btn-acpt-cncl btn-acpt-cncl"> Log out</button></a>
                        </div>
                    {% else %}
                    <div class="register">
                        <div class="login">
                            <a href="{% url 'user:login' %}"><button class="custom-btn-acpt-cncl btn-acpt-cncl"> Log in </button></a>
                        </div>
                        <div class="sing_up">
                            <a href="{% url 'users:index' %}"><button class="custom-btn-sing-up btn-sing-up"> Sing up </button></a>
                        </div>
                    </div>
                    {% endif %}
            </header>

        </div>
        <div class="wrapper">
            <a href="/polls"><button class="custom-btn-acpt-cncl btn-acpt-cncl">Polls</button></a>
        </div>
         <button id="Check-browser" class="custom-btn-acpt-cncl btn-acpt-cncl">Check your browser</button>
    </div>
</body>
</html>