API/urls.py
from django.urls import path

from . import views
#API
app_name = 'API'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('weather/', views.weather, name= 'weather')
]

main_page/urls.py
from django.urls import path

from . import views

app_name = 'main_page'
urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name= 'about_us')
]

polls_site/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main_page.urls')),

    #path('register/', include('users.urls')),
    path('user/', include('users.urls', namespace='user')),

    path('API/', include('API.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),
]

users/urls.py
# from django.urls import path, include
# from .views import UserLoginView, SignupView, UserLogoutView
#
# from . import views
#
# app_name = 'users'
#
# urlpatterns = [
#     path('',views.index, name= 'index'),
#     path('account/', views.account, name= 'account'),
#     path(r'login/', UserLoginView.as_view(), name= 'login'),
#     path(r'logout/', UserLogoutView.as_view(), name= 'logout'),
#     #path(r'singup/', SignupView.as_view(), name= 'singup'),
#     path(r'signup/', SignupView.as_view(), name= 'signup'),
#     path('google-auth/', include('social_django.urls', namespace='social')),
# ]


from django.urls import path, include
from .views import UserLoginView, SignupView, UserLogoutView

from . import views

app_name = 'users'

urlpatterns = [
    path('',views.index, name= 'index'),
    path('account/', views.account, name= 'account'),
    path(r'login/', UserLoginView.as_view(), name= 'login'),
    path(r'logout/', UserLogoutView.as_view(), name= 'logout'),
    path(r'singup/', SignupView.as_view(), name= 'singup'),
    #path('google-auth/', include('social_django.urls', namespace='social')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.core.validators import validate_slug
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    username = models.CharField(
        verbose_name="Username",
        max_length=150,
        unique=True,
        validators=[validate_slug],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    email = models.EmailField(verbose_name='E-mail', blank=True, unique=True, null=True)
    email_checked = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        #return '%s (%s)' % (self.get_full_name(), self.email)
        return '%s (%s)' % (self.username, self.email)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import User


class LoginForm(AuthenticationForm):
    pass

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")
        field_classes = {'username': UsernameField}

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render

from django.contrib.auth import login
from django.views.generic import FormView
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import LoginForm, SignupForm
from .models import User

#UPDATED
from polls.models import Vote, Question, Choice

class SignupView(FormView):
    template_name = 'users/singup.html'
    form_class = SignupForm

    def form_valid(self, form):
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        raw_password = form.cleaned_data['password1']
        user = User.objects.create_user(username, email, raw_password)
        login(self.request, user)
        #return HttpResponseRedirect(reverse('main_page:indexUn_log_sing'))
        return HttpResponseRedirect(reverse('main_page:index'))

class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

class UserLogoutView(LogoutView):
    template_name = 'users/logged_out.html'

def index(request):
    return render(request, 'users/register.html')

def account(request):
    #UPDATED
    vote = Vote.objects.filter(user= request.user)
    return render(request, 'users/account.html', {'vote' : vote})

users/templates/users/account.html
{% extends 'register_tampl.html' %}

{% block account %}
    {% for v in vote %}
    <p>{{ v }}</p>
    {% endfor %}
{% endblock %}

users/templates/users/logged_out.html
{% extends "register_tampl.html" %}

{% block logout %}
    {% load static %}
        <link rel="stylesheet" href="{% static 'users/style_logout.css'%}">
        <link rel="stylesheet" href="{% static 'users/google_btn.css'%}">
    <div class="logout_content">
        <h1>Logged out!</h1>

        <a href="{% url 'users:login'%}"><button class="custom-btn-acpt-cncl btn-acpt-cncl">Login again.</button></a>

        <div class="register">
            <p>If you don't hsve accaunt, you can always   </p>
            <a href="{% url 'users:singup' %}"><button class="custom-btn-acpt-cncl btn-acpt-cncl">Sing Up</button></a>
        </div>

        <div class="google-btn"><a href="{% url "user:social:begin" "google-oauth2" %}">
      <div class="google-icon-wrapper">
        <img class="google-icon" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg"/>
      </div>
        <p class="btn-text"><b>Log in with google</b></p></a>
    </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'register_tampl.html' %}


{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/style_login_sing.css'%}">
    <link rel="stylesheet" href="{% static 'users/google_btn.css'%}">
<div class="box">
    <h4 class="form-header">Log in</h4>

    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">

        {{ form }}

        <button type="submit" class="custom-btn-acpt-cncl btn-acpt-cncl">Log in</button>
    </form>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />

    <div class="google-btn">
        <a href="{% url "user:social:begin" "google-oauth2" %}">
      <div class="google-icon-wrapper">
        <img class="google-icon" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg"/>
      </div>
        <p class="btn-text"><b>Log in with google</b></p></a>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'register_tampl.html' %}



{% block register%}
    {% load static %}
        <link rel="stylesheet" href="{% static 'users/sryle_register.css'%}">
    <p>
    This Privacy Policy describes how we collect, use and process your data when you use our Site. By using the Site, you agree to the collection and use of information subject to this Privacy Policy.

    Please note that this Privacy Policy applies only to this Site. This Site may contain links to other sites not used or controlled by us. Links provided on this Site do not imply that we endorse or have reviewed such third party sites.

    The data protection policy has been prepared in accordance with the following legal acts

    Regulation (EU) of the European Parliament and of the Council of 27 April 2016 2016/679 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation) (hereinafter - BDAR);
    the Law of the Republic of Lithuania on the Legal Protection of Personal Data (hereinafter ADTAĮ);
    The Law of the Republic of Lithuania on Electronic Communications (hereinafter - ERĮ).
    </p>
    <div class="confirmation">
        <a href="{% url 'users:singup' %}"><button class="custom-btn-acpt-cncl btn-acpt-cncl">Accept</button></a>
        <a href="{% url 'main_page:index' %}"><button class="custom-btn-acpt-cncl btn-acpt-cncl">Cancel</button></a>
    </div>
{% endblock %}

users/templates/users/register_tampl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if request.user.is_authenticated %}
        <title>Account of user: {{ user.username }}</title>
        {% else %}
            <title>Polls</title>
    {% endif %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/style_ind.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'users/img/favicon.ico' %}">
</head>
<body>
    <div class="mainComponent">

        <div class="head">
            <header>
                <h1><a href="/">Home</a></h1>
                <div class="headlinks">
                    <nav>
                        <p><a href="/about_us">About us</a></p>
                        <p><a href="/polls">Polls</a></p>
                        <p><a href="/API">API</a></p>
                    </nav>
                </div>
            </header>

        </div>
            {% if request.user.is_authenticated %}
                    {% block account %}{% endblock %}
                {% else %}
                    {% block logout %}{% endblock %}
                    {% block content %}{% endblock %}
                    {% block singup %}{% endblock %}
                    {% block register%}{% endblock %}

{#                    <div class="register">#}
{#                        <p><a href="/user/singup">Sing Up</a></p>#}
{#                    </div>#}
            {% endif %}
    </div>
</body>
</html>

users/templates/users/singup.html
{% extends 'register_tampl.html' %}


{% block singup %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/style_login_sing.css'%}">
    <link rel="stylesheet" href="{% static 'users/google_btn.css'%}">
<div class="box">
    <h4 class="form-header">Sing up</h4>

    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">

        {{ form }}

        <button type="submit" class="custom-btn-acpt-cncl btn-acpt-cncl">Register</button>
    </form>
 <div class="google-btn" style="position: absolute; top: 90%; right: 35%;">
     <a href="{% url "user:social:begin" "google-oauth2" %}">
      <div class="google-icon-wrapper">
        <img class="google-icon" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg"/>
      </div>
        <p class="btn-text"><b>Sing up with google</b></p></a>
    </div>
</div>
{% endblock %}p